version: '3.7'

services:

  react-ui:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./app/git-react-app:/usr/src/app/git-react-app
       - /app/git-react-app/node_modules